baseurl = "https://unixvoid.com"
languageCode = "en-us"
title = "nsproxy-docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	author = "Matthew Faltys"
	description = "Nsproxy documentation."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/unixvoid/nsproxy"

	version = "0.2a"
	logo = "img/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "teal"

    [params.font]
    	text = "Source Sans Pro"
    	code = "Source Code Pro"


[social]
	twitter = "thefaltyone"
	github  = "mfaltys"
	email   = "mfaltys@gmail.com"


[[menu.main]]
	name   = "Nsproxy"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "API"
	url    = "api/"
	weight = 10

[[menu.main]]
	name   = "Basic Usage"
	url    = "basic_usage/"
	weight = 10

[[menu.main]]
	name   = "Building"
	url    = "building/"
	weight = 10

[[menu.main]]
	name   = "Configuration"
	url    = "configuration/"
	weight = 10

[[menu.main]]
	name   = "Redis Data Structures"
	url    = "redis_data_structures/"
	weight = 10

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
